version: "3"

services:
  httpd:
    image: xamp
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./html:/var/www/html

  database:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_super_secret_password
